### ISSUE TITLE
win7下为什么安装不成功？

### ISSUE THREAD

**Issue by libean** [deepcs233/jieba_fast#10]
提示错误，系统找不到指定的路径。: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib
这个怎么解决啊？
Python是3.6版本

**Comment by deepcs233** [comment]
你有安装VS吗，这个编译默认是使用的vs编译。你可以指定使用其他编译方式或者下载我编译好的lib（不过是基于3.5的）放到你的python安装目录下，具体位置参考readme。

**Comment by libean** [comment]
我电脑上有VS2015。编译好的lib在哪里下载？能做个基于3.6版本的lib么？谢谢！

**Comment by deepcs233** [comment]
lib就在仓库下的windows下，先试试。那就是你环境变量没设置好，没找到你的vs。
