### ISSUE TITLE
两次测试都慢于原版 在我的程序上慢了约3秒

### ISSUE THREAD

**Issue by bung87** [deepcs233/jieba_fast#11]
pip3安装
主要依赖posseg
命令行time的结果 
处理了4691份短文本
并使我的程序下降了约0.01的准确度。

**Comment by deepcs233** [comment]
posseg里面的viterbi算法感觉用的不多，并没有用c重写过。所以你的慢了3s和0.01的准确度都有可能是误差。我之后有空会考虑优化一下

**Comment by bung87** [comment]
忘了说 我还加载了自定义词典 无频次和词性标注的。
可能是应用场景有点问题 总之posseg明显比jieba.cut慢（在原版上也是）
我主要用来判断词语或短语的词性(多数是词语) 因为没有发现对应的接口 都统一用posseg.cut
而且在原版上启用并行分词也会使我的程序下降，后来我的程序改了逻辑，不再依赖词性判断了，程序执行效率有了质的飞跃，用了jieba_fast后又进一步得到提升:）

**Comment by deepcs233** [comment]
看了下代码，posseg中的viterbi算法比finalseg里的viterbi复杂的多，可以优化的部分有很多，近期考虑优化一下。原jieba里的并行有点坑的，最好是直接扔一个大文本进去，4000+短文本起不到什么效果。

**Comment by bung87** [comment]
我看了jieba和另外一个库 都没有查单个词 词性的专门接口这是为啥 ？如果它能根据上下文切分并标注词性反过来根据单独成词的概率直接给出词性 这样会遇到什么问题吗？

**Comment by deepcs233** [comment]
没太懂你的意思，词性不能单独给出，需要联合上下文一起分析出来。所以需要先切好词，再根据切的词序列分析词性，这步分析也是走的viterbi，复杂度也不低。
