### ISSUE TITLE
子package里import了jieba 而依赖并未在setup列出

### ISSUE THREAD

**Issue by bung87** [deepcs233/jieba_fast#12]
原版的python子package已经完全包含进来了，按理说可以安全的替换掉import jieba,
这带来的另外一个副作用是如果使用子package就会import jieba 使得jieba_fast和jieba的default_logger都起作用，console里会显示两次load信息。

**Comment by deepcs233** [comment]
嗯嗯,这是个问题,我会在下一个版本进行fix

**Comment by deepcs233** [comment]
已在最新版本中解决依赖旧jieba的问题

**Comment by deepcs233** [comment]
@bung87
