### ISSUE TITLE
内存泄漏的问题

### ISSUE THREAD

**Issue by bojone** [deepcs233/jieba_fast#2]
我训练Word2Vec，代码大概是
<pre><code>import pymongo
db = pymongo.MongoClient().weike.content_lectures

import jieba

class Document:
    def __iter__(self):
        for t in db.find(no_cursor_timeout=True):
            yield jieba.lcut(t['content'])

import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

from gensim.models import Word2Vec

word2vec = Word2Vec(Document(), size=128, window=10, min_count=5, sg=1, negative=10, workers=4, iter=10)
word2vec.save('weike.word2vec')</code></pre>

这个代码一直保持比较低的内存消耗。

然而，如果将jieba换成你写的jieba_fast，内存就一直飙升，直到最后进程被杀。分别在ubuntu和centos都测试过。

**Comment by deepcs233** [comment]
经检查是一些PyObject没有释放的缘故，已修复内存泄漏的问题
