### ISSUE TITLE
jieba_fast初始化是并发安全的吗？

### ISSUE THREAD

**Issue by zyshin** [deepcs233/jieba_fast#20]
第一次调用 `jieba_fast.lcut` 会首先构建trie树写入 `/tmp/jieba.cache` 
想知道如果两个线程同时调用 `jieba_fast.lcut` 会如何？两个进程同时调又会如何？

**Comment by deepcs233** [comment]
并发安全性与原生jieba是一致的。不管是多进程还是多进程都是安全的，除了第一个线程or进程会创建临时文件，之后的线程or进程在cache建立后便会直接读取。

**Comment by zyshin** [comment]
如果两个进程使用了不同的自定义词典，可以共享同一个临时文件吗？
