### ISSUE TITLE
jieba.set_dictionary和jieba.load_userdict有何区别

### ISSUE THREAD

**Issue by wwfcnu** [deepcs233/jieba_fast#27]
jieba.set_dictionary和jieba.load_userdict有何区别

**Comment by XiaoxiaoyuZhu** [comment]
已收到

**Comment by deepcs233** [comment]
前者使用自定义的字典直接代替jieba内置的字典，后者是添加一个用户词典以补充内置的词典。

**Comment by wwfcnu** [comment]
jieba.load_userdict和jieba.add_word有什么区别

**Comment by deepcs233** [comment]
前面是字典，后面是单个词语
