### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cbzhuang** [deepcs233/jieba_fast#4]
我最近使用jieba_fast进行分词，在windows平台上会出现python直接崩溃的情况，ubuntu上也出现”Segmentation fault (core dumped)“的错误，python版本分别是3.6.3和3.6.1。
![selection_617](https://user-images.githubusercontent.com/25291084/35478277-dfacac0c-0413-11e8-99de-dbdd6a0638ba.png)

**Comment by deepcs233** [comment]
你好，关于Py3的bug已经修复。卸载此版本再重新安装一次即可
