### ISSUE TITLE
posseg.cut 对自定义词典不工作

### ISSUE THREAD

**Issue by Levstyle** [deepcs233/jieba_fast#9]
也就是说，当使用posseg.cut进行分词和词性标注的时候，自定义词典根本就不起作用。而原python版的结巴，不存在此问题。

**Comment by deepcs233** [comment]
方便的话可以贴一下case及系统环境，python版本等信息吗
谢谢

**Comment by deepcs233** [comment]
@Levstyle 你的问题应该在0.53版本中被fix，可以update一下
